### ISSUE TITLE
Improve documentation for boolean flags with `true` as default value

### ISSUE THREAD

**Issue by gmargaritis** [docker/cli-docs-tool#47]
@thaJeztah @crazy-max Following up on our discussion in https://github.com/docker/cli/pull/4259#discussion_r1483128896 and in https://github.com/docker/cli-docs-tool/pull/19#issuecomment-1937006531.

We should add values in `Type` and `Default` columns for boolean flags that have `true` as default value.

I'll be opening a PR soon!

**Comment by crazy-max** [comment]
SGTM
